### ISSUE TITLE
Web应用防火墙购买入口

### ISSUE THREAD

**Issue by Miss-Qiao** [huaweicloudDocs/waf#1]
开通WAF > 购买Web应用防火墙 页面，步骤2中的图片，Step4 我没有找到这个入口，根据前3步的指引，找到的是“购买Web应用防火墙”的入口，是不是我点击的控制台入口不正确？
![image](https://user-images.githubusercontent.com/42136677/83852745-d87f6b80-a746-11ea-82c4-89921ce38961.png)

**Comment by wuzhen9** [comment]
已修改

**Comment by wuzhen9** [comment]
已修改
